name    'alkivi-alkivi_base'
version '0.0.3'
source 'https://github.com/alkivi-sas/puppet-alkivi_base'
author 'alkivi'
license 'LGPLv3'
summary 'Controls basic configuration of alkivi server'
description 'Setup basic users, ssh keys, packages, configure console, keymap, tzdata and stuff'
project_page 'https://github.com/alkivi-sas/puppet-alkivi_base'
dependency 'puppetlabs/stdlib', '>=3.x'
dependency 'puppetlabs/ntp', '>=2.x'
dependency 'adrien/alternatives', '>=0.1.1'
dependency 'attachmentgenie/locales', '>=1.0.2'
dependency 'alkivi/console_data', '>=0.0.1'
