#!/bin/bash

set -e

RED='\e[1;31m'
GREEN='\e[1;32m'
YELLOW='\e[1;33m'
NOCOLOR='\e[0m'
log()
{
    ACTION=$1
    if [ -z "$ACTION" ]; then
        error "Wrong call to log_action, you must pass an action"
        exit 1
    fi

    printf "%-70s ...   " "$ACTION"

}

ok()
{
    if [ -z "$1" ]; then
        ACTION="OK"
    else
        ACTION="$1"
    fi
    ack "$ACTION" "$GREEN"
}

doing()
{
    if [ -z "$1" ]; then
        ACTION="TODO"
    else
        ACTION="$1"
    fi
    ack "$ACTION" "$YELLOW"
}

error()
{
    if [ -z "$1" ]; then
        ACTION="KO"
    else
        ACTION="$1"
    fi
    ack "$ACTION" "$RED"
}

ack()
{
    ACTION="$1"
    COLOR="$2"
    printf "${COLOR}%s${NOCOLOR}\n" "$ACTION"
}

USER='root'
HOST=$1
PORT=22

# Fetch password
PASS_FILE="/root/.passwd/hosts/$HOST"
if [ ! -e $PASS_FILE ];
then
    error "File $PASS_FILE does not exist"
    exit 1
fi

PASSWORD=`cat /root/.passwd/hosts/$HOST`
SSH_BASE="ssh -p $PORT $USER@$HOST"

# Test via fping
fping $HOST

log "Updating password for alkivi to 'alkivi'"
(
$SSH_BASE passwd alkivi  <<EOF
alkivi
alkivi
EOF
) > /dev/null 2>&1
ok

log "Press enter when support is done"
read

log "Restoring password for alkivi"
(
$SSH_BASE passwd alkivi  <<EOF
$PASSWORD
$PASSWORD
EOF
) > /dev/null 2>&1
ok
